environment: dev
apiurl: "https://v9qj78-3000.csb.app"
apitoken: "123"
module:
  server-list:
    player-count:
      enabled: true
    motd:
      enabled: true
      line_1: "&7play.&6&lFabledRealms&7.net"
      line_2: "&eStart your story on May 4th 2024"
  character-creation:
    default-level: 1
    default-exp: 0
    default-balance: 10
    max-characters: 5
    npc: "Character Creator"
dungeon:
  item-per-chest: 5
world:
  name: "dungeon_world"