settings:
  databases: #Don't touch this unless you're a Josh or Griimm
    player-data:
      host: "srv2.ethera.net"
      port: "3306"
      database: "s835_PlayerData"
      username: "u835_6QampAlMBY"
      password: "YlR=9!4MY!6NeQ+sIRZTRe.Y"
module:
  server-list:
    player-count:
      enabled: true
    motd:
      enabled: true
      line_1: "&7play.&6&lFabledRealms&7.net"
      line_2: "&eStart your story on May 4th 2024"
  character-creation:
    default-level: 1
    default-exp: 0
    default-balance: 10
    max-characters: 5