name: Update Pom Version and Deploy Package

on:
  workflow_run:
    workflows: [Generate Prod Releases]
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d_%H%M')"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Modify POM version using xmlstarlet
        id: xml_replace
        uses: Mudlet/xmlstarlet-action@master
        with:
          args: ed -L --update "/project/version" -v "${{ steps.date.outputs.date }}" "pom.xml"

      - name: Publish package
        run: |
          echo "Deploying Maven package..."
          mvn --batch-mode -DuseGitHubPackages=true deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#run
